package at.spengergasse.doctor.models.patients;

import at.spengergasse.doctor.models.BaseEntity;
import at.spengergasse.doctor.models.shared.InsuranceNumber;
import at.spengergasse.doctor.models.shared.PhoneNumber;
import jakarta.persistence.Column;
import jakarta.persistence.Embedded;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.ToString;


// ANAEMIC domain model  -> only properties, no behavior
// RICH domain model     -> properties + behavior (methods)


// Java Bean Validation
// https://www.baeldung.com/java-validation

// @NotBlank @Size(max = 50)                // -> Java Bean Validation
// @Column(nullable = false, length = 50)   // -> DB Column Definition


/*
Our Jpa Provider (Hibernate) will create the following table structure:

    CREATE TABLE patient (
        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        firstname           VARCHAR(50) NOT NULL,
        lastname            VARCHAR(50) NOT NULL,
        insurance_number    VARCHAR(10) NOT NULL,
        mobile              VARCHAR(255)
    );
 */


// Lombok
@Getter
@ToString(callSuper = true)
// @NoArgsConstructor
// @AllArgsConstructor

// JPA
@Entity
@Table(name = "patient")
public class Patient extends BaseEntity {

    // @NotBlank @Size(max = 50)
    @Column(nullable = false, length = 50)
    private String firstname;

    // @NotBlank @Size(max = 50)
    @Column(nullable = false, length = 50)
    private String lastname;

    // Embedded Rich Type (Domain Primitive)
    // (-> has insurance_number in the table structure !)
    @Embedded
    private InsuranceNumber insuranceNumber;

    // Variante 1:
    // Here we take the default column mapping of the embedded PhoneNumber:
    @Embedded
    private PhoneNumber mobile;

    // Variante 2:
    // Here we override the column mapping of the embedded PhoneNumber:
    // @Embedded
    // @AttributeOverride(name = "value", column = @Column(name = "mobile", nullable = true))
    // private PhoneNumber mobile;

    // JPA Ctor
    protected Patient() {
    }

    // Business Ctor
    public Patient(String firstname, String lastname, InsuranceNumber insuranceNumber, PhoneNumber mobile) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.insuranceNumber = insuranceNumber;
        this.mobile = mobile;
    }
}
