package at.spengergasse.doctor.models.staff;


import at.spengergasse.doctor.models.BaseEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import lombok.Getter;
import lombok.ToString;


// ANAEMIC domain model  -> only properties, no behavior
// RICH domain model     -> properties + behavior (methods)

// Java Bean Validation
// https://www.baeldung.com/java-validation

// @NotBlank @Size(max = 50)                // -> Java Bean Validation
// @Column(nullable = false, length = 50)   // -> DB Column Definition


/*
Our Jpa Provider (Hibernate) will create the following table structure:

    CREATE TABLE DOCTOR (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        firstname   VARCHAR(50) NOT NULL,
        lastname    VARCHAR(50) NOT NULL,
        email       VARCHAR(255) NOT NULL,
        CONSTRAINT uk_doctor_email UNIQUE (email)
    );
*/


@Getter
@ToString(callSuper = true)
// @NoArgsConstructor
// @AllArgsConstructor

@Entity
@Table(name = "doctor",
    uniqueConstraints = {
        @UniqueConstraint(name = "uk_doctor_email", columnNames = "email")
})
public class Doctor extends BaseEntity {

    // @NotBlank @Size(max = 50)
    @Column(nullable = false, length = 50)
    private String firstname;

    // @NotBlank @Size(max = 50)
    @Column(nullable = false, length = 50)
    private String lastname;

    @Column(nullable = false)
    private String email;

    // JPA Ctor
    protected Doctor() {
    }

    // Business constructor
    public Doctor(String firstname, String lastname, String email) {
        this.firstname = firstname;
        this.lastname = lastname;
        this.email = email;
    }
}
