package at.spengergasse.doctor.models.appointments;

import at.spengergasse.doctor.models.BaseEntity;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.ToString;

import java.time.LocalDateTime;

/*
Single Table Inheritance Strategy:
    Subclasses (CancelledAppointmentState and ConfirmedAppointmentState) have their columns in this single table.

Our Jpa Provider (Hibernate) will create the following table structure:
    CREATE TABLE APPOINTMENT_STATE (
        id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        appointment_id      BIGINT NOT NULL UNIQUE,
        created             TIMESTAMP(6) NOT NULL,
        doctor_id           BIGINT NOT NULL,
        infotext            VARCHAR(255),
        start_time          TIME(0) NOT NULL,
        end_time            TIME(0) NOT NULL,
        type                VARCHAR(31) NOT NULL CHECK (type IN ('Cancelled', 'Confirmed'))
    );
 */


// Lombok
@Getter
@ToString(callSuper = true)

// JPA
@Entity
// @Table(name = "appointment_state")

// JPA Inheritance (Single Table Strategy = One Table for all Subclasses)
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "type")
public abstract class AppointmentState extends BaseEntity {

    // Owner Side / FK-Side (Foreign Key Side)
    // (-> has apppointment_id in the table structure !)
    @OneToOne(fetch = FetchType.LAZY, optional = true)
    @JoinColumn(name = "appointment_id", nullable = true, unique = true)
    private Appointment appointment;

    @Column(nullable = false)
    private LocalDateTime created;

    // JPA Ctor
    protected AppointmentState() {
    }

    // Business Ctor
    public AppointmentState(Appointment appointment, LocalDateTime created) {
        this.appointment = appointment;
         this.created = created;
    }
}
