package at.spengergasse.doctor.models.appointments;

import at.spengergasse.doctor.models.BaseEntity;
import at.spengergasse.doctor.models.patients.Patient;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.ToString;

import java.time.LocalDate;
import java.time.LocalDateTime;

/*
Our Jpa Provider (Hibernate) will create the following table structure:

    CREATE TABLE APPOINTMENT (
        id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        patient_id      BIGINT NOT NULL,
        date            DATE NOT NULL,
        created         TIMESTAMP(6) NOT NULL,
        CONSTRAINT uk_patient_date UNIQUE (patient_id, date)
    );
*/

// Lombok
@Getter
@ToString(callSuper = true)
// @NoArgsConstructor
// @AllArgsConstructor

// JPA
@Entity
@Table(name = "appointment", uniqueConstraints = {
    @UniqueConstraint(name = "uk_patient_date",
        columnNames = {"patient_id", "date"})
})
public class Appointment extends BaseEntity {

    @Column(nullable = false)
    private LocalDate date;

    @Column(nullable = false)
    private LocalDateTime created;

    // Owner Side / FK-Side (Foreign Key Side)
    // (-> has patient_id in the table structure !)
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "patient_id", nullable = false)
    private Patient patient;

    // Inverse Side / LifeCycle Chef
    // (-> has no column in the table structure !)
    @OneToOne(mappedBy = "appointment",
        fetch = FetchType.LAZY, cascade = CascadeType.ALL, orphanRemoval = true)
    private AppointmentState currentState;


    // JPA Ctor
    protected Appointment() {
    }

    // Business Ctor
    public Appointment(LocalDate date, LocalDateTime created, Patient patient) {
        this.date = date;
        this.created = created;
        this.patient = patient;
    }

    /* EASY but BAD: Generic Method to change State */

    // Lifecyle Chef (parent) sets the current state (child)
    public void setCurrentState(AppointmentState currentState) {
        this.currentState = currentState;
    }


    /*
    BETTER Real Business Methods

    public void confirm(Doctor doctor, TimeSlot slot, String info) {
        var state = new ConfirmedAppointmentState(this, LocalDateTime.now(), doctor, slot, info);
        this.currentState = state;
    }

    public void cancel(String reason) {
        var state = new CancelledAppointmentState(this, LocalDateTime.now(), reason);
        this.currentState = state;
    }
     */
}
